config/routes.rb
Rails.application.routes.draw do


  

  #create show and etc
  resources :shoes


	#homepage
  root 'static_pages#home'

  #user sign in
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #user sign-up and etc
  resources :users 

  #user add to cart
  resource :cart, only: [:show] do
    put 'add/:shoe_id', to: 'carts#add', as: :add_to
    put 'remove/:shoe_id', to: 'carts#remove', as: :remove_from
  end
  
## Braintree payments
  # Payment Info
resources :transactions, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  


  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_shoes = Shoe.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:shoe_id]
    render json: current_user.cart_count
  end

  def remove
    $redis.srem current_user_cart, params[:shoe_id]
    render json: current_user.cart_count
  end

  private



  def current_user_cart

        unless logged_in?
      flash[:danger] = "Access denied."
       redirect_to root_path
     else 
    "cart#{current_user.id}"
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<div id="mycart">
<div class="container">

    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> shoes!</p>
  </div>

  <% @cart_shoes.each do |shoe|%>
 <p>
 <% if shoe.photos.nil? %>
    <strong><%=image_tag shoe.photos[0] %></strong>
    <%end%>
    </p>

    <p>
  <strong>Brand:</strong>
  <%= shoe.brand %>
</p>

<p>
  <strong>Description:</strong>
  <%= shoe.description %>
</p>

  <%=link_to "" , data: {targetUrl: remove_from_cart_path(shoe)} do%>
        <i class="fi-x right">clear</i>
<% end %>

      <%end%>

      <%=link_to "Checkout", new_transaction_path, class: "button" unless current_user.get_cart_shoes.blank?%>
      </div>  

      </div>