config/routes.rb
Rails.application.routes.draw do


  

  #create show and etc
  resources :shoes


	#homepage
  root 'static_pages#home'

  #user sign in
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #user sign-up and etc
  resources :users 

  #user add to cart
  resource :cart, only: [:show] do
    put 'add/:shoe_id', to: 'carts#add', as: :add_to
    put 'remove/:shoe_id', to: 'carts#remove', as: :remove_from
  end
  
## Braintree payments
  # Payment Info
resources :transactions, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :load_braintree_data, only: [:show, :edit]

  def show
  end

  def new
    gon.client_token = generate_new_client_token
  end

  def edit
    @credit_card = current_user.default_credit_card
    @tr_data = edit_customer_tr_data
  end

  def create
    @result = Braintree::Transaction.sale(
              amount: current_user.cart_total_price,
              payment_method_nonce: params[:payment_method_nonce])
    if @result.success?
      current_user.purchase_cart_shoes!
      redirect_to root_url, notice: "Congraulations! You've purchased new shoes successfully!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_new_client_token
      render :new
    end
  end

  private

  def generate_new_client_token
    Braintree::ClientToken.generate
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/new.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
  <p>Please enter your payment details:</p>
  <%= form_tag transactions_path do%>
    <div id="dropin"></div>
    <%=submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1" %>
  <%end%>
</div>
<script src="https://js.braintreegateway.com/v2/braintree.js"></script>

<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>