config/routes.rb
Rails.application.routes.draw do


  

  #create show and etc
  resources :shoes


	#homepage
  root 'static_pages#home'

  #user sign in
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #user sign-up and etc
  resources :users 

  #user add to cart
  resource :cart, only: [:show] do
    put 'add/:shoe_id', to: 'carts#add', as: :add_to
    put 'remove/:shoe_id', to: 'carts#remove', as: :remove_from
  end
  
## Braintree payments
  # Payment Info
resources :transactions, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shoe.rb
class Shoe < ApplicationRecord

	validates :name, presence: true
	validates :brand, presence: true
	validates :price, presence: true
	validates :description, length: { minimum:10, message: "description is too short" }

	belongs_to :user
	
	has_many :shoe_categories
	has_many :categories, through: :shoe_categories

	has_many :purchases
	has_many :buyers, through: :purchases

	attr_accessor :photos
  mount_uploaders :photos, ImageUploader

  include PgSearch

 	pg_search_scope :search_full_text,
 		:using => {
 		:tsearch => {:any_word => true }
 	},

		:against => {
			:brand => 'A',
			:name => 'B'
		}

	def cart_action(current_user_id)
  	if $redis.sismember "cart#{current_user_id}", id
    	"Remove from"
  	else
    	"Add to"
  	end
	end
	
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]
  before_action :admin_only, :except => [:create, :show, :new, :edit, :update, :destroy]
  # GET /shoes
  # GET /shoes.json
  def index

    if params[:query].present?
      @shoes = Shoe.search_full_text(params[:query]).page params[:page]
    elsif params[:category_id]
      respond_to do |format|
      format.js
      format.html
    end
      @shoes = Category.find(params[:category_id]).shoes.page params[:page]
    else
      @shoes = Shoe.all.page params[:page]
    end
  end



  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])
    @cart_action = @shoe.cart_action current_user.try :id
  end

  # GET /shoes/new
  def new
    @shoe = Shoe.new
  end

  # GET /shoes/1/edit
  def edit
    unless current_user.try(:admin?)
      unless logged_in? and current_user.id == @shoe.user_id
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = current_user.shoes.new(shoe_params)

      if @shoe.save
         flash[:notice] = "Shoe was successfully created."
         redirect_to @shoe
      else
        flash[:danger] = "Shoe was not successfully created."
        render new
      end
    end
  

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
      if @shoe.update(shoe_params)
        flash[:notice] = "Shoe was successfully updated."
        redirect_to @shoe
      else
        flash[:danger] = "Shoe was not successfully updated."
        render :edit
      end
    end
  

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url, notice: 'Shoe was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = Shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.require(:shoe).permit(:name, :brand, :shoe_size, :price, :description, category_ids:[], photos:[])
    end
    
   def admin_only
      unless current_user.try(:admin?)
        flash[:danger] = "Access denied."
        redirect_to root_path
      end
    end

end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_edit_form.html.erb
<%= form_for(shoe) do |f| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :shoe_size %>
    <%= f.number_field :shoe_size %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

<div class="form-group ">
<%= f.label :Tag %><br>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :content %><br>
</div>

<div class="form-group ">
<%= f.label :photos %><br>
<%= f.file_field :photos, multiple: true %><br>

 <%= f.check_box :remove_photos %>
    Remove Photos<br>
</div>

<div class="form-group ">
<button><%= link_to 'Delete Shoe?', shoe, method: :delete, data: {confirm: 'Are you sure you want to delete this shoe?' } %></button>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/_form.html.erb
<%= form_for(shoe) do |f| %>
  <% if shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% shoe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :brand %>
    <%= f.text_field :brand %>
  </div>

  <div class="field">
    <%= f.label :shoe_size %>
    <%= f.number_field :shoe_size %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

<div class="form-group ">
<%= f.label :Tag %><br>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :content %><br>
</div>

<div class="form-group ">
<%= f.label :photos %><br>
<%= f.file_field :photos, multiple: true %><br>

 <%= f.check_box :remove_photos %>
    Remove Photos<br>
</div>

<div class="form-group ">
<button><%= link_to 'Delete Listing', shoe, method: :delete, data: {confirm: 'Are you sure you want to delete this shoe?' } %></button>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/_shoes_index.html.erb
<% @shoes.each do |shoe| %>
<div class="col-md-5">
  <div class="thumbnail">
    <% if shoe.photos? %>
    <%= image_tag(shoe.photos[0]) %>
    <%end%>
    <div class="caption">
      <h5><b>Name: </b><%= link_to shoe.name, shoe_path(shoe.id) %></h5>
      <h5><b>Brand: </b><%= link_to shoe.brand, shoe_path(shoe.id) %></h5>
      <h5 class="subheader"><b>RM </b><%= shoe.price.to_i %></h5>
      <h5 class="subheader"><b>Description: </b><%= shoe.description %>
      <% if shoe.user.username? %>
      <h5 class="subheader"><b>Owned by: </b><%= shoe.user.username %>
      <% end %>
    </div>
  </div>
  </div> <!-- col-md-4 -->
  <%end%>
  <div class="col-md-12 col-md-offset-4">
    <%= paginate @shoes %>
  </div>

</div>

app/views/shoes/all_shoe.html.erb
<p id="notice"><%= notice %></p>

<h1>Shoes</h1>

<table>
  <thead>
    <tr>
      <th>Shoe ID</th>
      <th>Shoe Name</th>
      <th>Shoe Brand</th>
      <th>Shoe price</th>
      <th>Last Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoes.order(:id).each do |shoe| %>
      <tr>
        <td><%= shoe.id %></td>
        <td><%= shoe.name %></td>
        <td><%= shoe.brand %></td>
        <td><%= shoe.price%></td>
        <td><%= shoe.description%></td>
        
        <td><%= link_to 'Show', shoe %></td>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shoes/edit.html.erb
<h1>Editing Shoe</h1>

<%= render 'edit_form', shoe: @shoe %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<div class="container">
  <div class="row">


    <p class="lead"><b><%= "Welcome, " + current_user.username if !current_user.nil? %></b>
      <p id="notice"><%= notice %></p>

  

       
      <div class="col-md-2">
        <div class="list-group">
          <%= link_to "All Shoes", shoes_path, class: "list-group-item"%>
          <% Category.all.order(:content).each do |c| %>
          <%= link_to c.content, root_path(category_id: c.id), class: "list-group-item", remote: true %>
          <% end %>
        </div>
        </div><!-- col-md-2-->

        <div class="col-md-10">
        <div id="shoes-index">
        <% if @shoes.blank?%>
        <h3> Sorry, there's no <%= params[:query] %> shoe's found!</h3>
        <%end%>
          <%= render "shoes_index", locals: { shoes: @shoes } %>

        </div>
    
      </div>

    </div>
     
  </div>

app/views/shoes/index.js.erb
$("#shoes-index").html("<%= escape_javascript(render partial: 'shoes_index', locals: { products: @shoes }) %>")

app/views/shoes/new.html.erb
<h1>New Shoe</h1>

<%= render 'form', shoe: @shoe %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <strong> <b><%= (current_user && current_user.purchase?(@shoe)) ? "Recently Purchased" : "" %></b></strong>
</p>

<% if  @shoe.photos.nil? %>
<%= image_tag(@shoe.photos[0])%>
<%end%>
<p>
  <strong>Owned by:</strong>
  <%= @shoe.user.username %>
</p>
<p>
  <strong>Brand:</strong>
  <%= @shoe.brand %>
</p>
<p>
  <strong>Shoe size:</strong>
  <%= @shoe.shoe_size %>
</p>
<p>
  <strong>Price:</strong>
  <%= @shoe.price.to_i %>
</p>
<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>
<p>
  <strong>Category:</strong>
  <% @shoe.categories.each do |category| %>
  <%= category.content %>
  <% end %>
</p>

<p>
<% if logged_in? %>
  <strong><%=link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@shoe), removeUrl: remove_from_cart_path(@shoe)} do%></strong>
    <i class="fi-shopping-cart"></i>
    <span><%=@cart_action%></span> Cart
  <%end%>
<%end%>
</p>
<% if logged_in? and current_user.id == @shoe.user_id %>
<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>
<% end %>

<% if current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>
<% end %>