config/routes.rb
Rails.application.routes.draw do


  

  #create show and etc
  resources :shoes


	#homepage
  root 'static_pages#home'

  #user sign in
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  #user sign-up and etc
  resources :users 

  #user add to cart
  resource :cart, only: [:show] do
    put 'add/:shoe_id', to: 'carts#add', as: :add_to
    put 'remove/:shoe_id', to: 'carts#remove', as: :remove_from
  end
  
## Braintree payments
  # Payment Info
resources :transactions, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    
    <nav>
<ul class="nav navbar-nav navbar-left">

     <li><%= link_to "SHOE LACE", root_path %></li>
   
        <form class="navbar-form navbar-left">
        <%= form_tag shoes_path, method: :get do %>
          <div class="input-group" style="width: 500px;">
            <%= text_field_tag :query, params[:query], placeholder: "What shoes are you looking for?", class: "form-control" %>
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit">
                <i class="glyphicon glyphicon-search"></i>
              </button>
            </div>
            <% end %>
          </div>
        </form>

     </ul>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Home", root_path %></li>

        <% if logged_in? %>
        <li><%= link_to cart_path do%>
         My Cart
    (<span class="cart-count"><%=current_user.cart_count%></span>)
        <% end %>
        </li>
          <li><%= link_to "Sell Your Shoe!", new_shoe_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user)%></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, :method=>'delete' %>
              </li>
             
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign in with Facebook", "/auth/facebook" %></li>
        <% end %>

        <% if current_user.try(:admin?) %>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">Admin
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
        <li><%= link_to 'Show All Users', users_path %></li>
        <li><%= link_to 'Show All Shoes', shoes_path %></li>
        <% end %>
      
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoelace</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag 'application'%>
  </head>
  <%= render "layouts/alerts"%>
	<%= render "layouts/header" %>
  <body>
    <%= yield %>
  </body>

  
</html>